// GENERATED by scripts/sync-mediapipe-assets.mjs. Do not edit by hand.
//
// Both paths are content-addressed so they can be served immutable. Run
// `npm run sync:assets` after changing the MediaPipe version or the model
// bundle, and commit the result.

/** Directory FilesetResolver loads the WASM runtime from. */
export const WASM_BASE_PATH = "/mediapipe/wasm-235adcc4";

/** Face Landmarker model bundle. */
export const MODEL_ASSET_PATH = "/models/face_landmarker.64184e22.task";
